### ISSUE TITLE
Cookiecutter template

### ISSUE THREAD

**Issue by V-FEXrt** [Albert-Gao/kotlin-native-mobile-multiplatform-example#1]
Have you considered making a [cookie cutter](https://github.com/audreyr/cookiecutter) template of this repo?

Doing so would greatly ease the setup of a new project. If you don't plan to/don't want to do so, then I would be willing to fork and do it myself.

Thoughts?

**Comment by Albert-Gao** [comment]
Thanks for asking.

No plan to do this.
Feel free to fork :)
