### ISSUE TITLE
Missing gradle files breaks build

### ISSUE THREAD

**Issue by V-FEXrt** [Albert-Gao/kotlin-native-mobile-multiplatform-example#2]
The files 

```
gradle/wrapper/gradle-wrapper.jar
gradle/wrapper/gradle-wrapper.properties
```

are currently being ignored by the .gitignore, but they shouldn't be as they are required for gradle to build properly.

See [this](https://stackoverflow.com/questions/20348451/why-should-the-gradle-wrapper-be-committed-to-vcs) for more information on the issue

**Comment by Albert-Gao** [comment]
Thanks !
