### ISSUE TITLE
Lower development target

### ISSUE THREAD

**Issue by Iliasvw** [Albert-Gao/kotlin-native-mobile-multiplatform-example#3]
Hello

I am currently trying to build a project like yours to use Kotlin for cross-platform development. It's working quite well but I do have one problem. In Xcode, the development target is 11.2. When I lower the development target too something below 11.0, all the builds will fail and running on emulator and a real device won't work.

The error I got is: 
"Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_SOSSample", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

Does Kotlin Native not support the armv7? Maybe any fix?

Thanks in advance
Ilias

**Comment by olonho** [comment]
Yes, Kotlin/Native currently only support arm64 targets, which covers Apple devices starting iPhone 5S.  And we do not plan to add such support.

**Comment by Albert-Gao** [comment]
Thanks @olonho !

@Iliasvw I think we can safely close this issue now as @olonho has given the answer and properly the most suitable person for answering KN questoin 😄
